In [3]:
import numpy as np

In [2]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(data)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


In [3]:
data1 = [[1, 2, 3, 4, 5], [1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
arr = np.array(data1)
arr

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [4]:
t = np.arange(10)
t


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import pandas as pd 

In [6]:
dict = {'Felipe' : 32, 'Fernanda': 31, 'Maria': 30}

dic = pd.Series(dict)
dic

Felipe      32
Fernanda    31
Maria       30
dtype: int64

In [7]:
dic.to_dict()


{'Felipe': 32, 'Fernanda': 31, 'Maria': 30}

In [8]:
nomes = ['Felipe', 'Fernanda', 'Barbosa', 'Beatriz']
valores = [21, 27, 35, 22]

t = pd.Series(valores, index=nomes)
print(t)

Felipe      21
Fernanda    27
Barbosa     35
Beatriz     22
dtype: int64


In [9]:
pd.notna(t)

Felipe      True
Fernanda    True
Barbosa     True
Beatriz     True
dtype: bool

In [10]:
import pandas as pd 

df = pd.DataFrame(np.arange(0, 10, 2))
df

,0
0,0
1,2
2,4
3,6
4,8


In [11]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [12]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"), index=[ "Ohio", "Texas", "Colorado"])
df1

,b,c,d
Ohio,0.0,1.0,2.0
Texas,3.0,4.0,5.0
Colorado,6.0,7.0,8.0


In [13]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=["Utah", "Ohio", "Texas", "Oregon"])
df2

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [14]:
df1.add(df2, fill_value=0)

,b,c,d,e
Colorado,6.0,7.0,8.0,NaN
Ohio,3.0,1.0,6.0,5.0
Oregon,9.0,NaN,10.0,11.0
Texas,9.0,4.0,12.0,8.0
Utah,0.0,NaN,1.0,2.0


In [15]:
# Somar 2 df e preencher valores com NaN com 0

df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))

In [16]:
df2.loc[1, 'b'] = np.nan

In [17]:
df1 + df2

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,NaN
1,9.0,NaN,13.0,15.0,NaN
2,18.0,20.0,22.0,24.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [18]:
df1.add(df2, fill_value=0)

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,4.0
1,9.0,5.0,13.0,15.0,9.0
2,18.0,20.0,22.0,24.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [19]:
df1.reindex(columns=df2.columns, fill_value=0)

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,0
1,4.0,5.0,6.0,7.0,0
2,8.0,9.0,10.0,11.0,0


In [20]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [21]:
# Quando subtraimos o arr[0] que é a primeira linha do array, do array como um todo, ele faz a subtração uma vez para cada linha, então primeiro
# ele subtrai ele dele mesmo, trazendo 0 para todas as colunas da primeira linha
# depois ele faz isso para as linhas de baixo, onde o valor da coluna for semelhante

arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [22]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),  )
frame

,b,d,e
0,0.0,1.0,2.0
1,3.0,4.0,5.0
2,6.0,7.0,8.0
3,9.0,10.0,11.0


In [23]:
#iloc olha para o inteiro, enquanto loc olha para rótulos (nomes dos indices)
series = frame.iloc[0]
series


b    0.0
d    1.0
e    2.0
Name: 0, dtype: float64

In [24]:
frame - series

,b,d,e
0,0.0,0.0,0.0
1,3.0,3.0,3.0
2,6.0,6.0,6.0
3,9.0,9.0,9.0


In [25]:
frame

,b,d,e
0,0.0,1.0,2.0
1,3.0,4.0,5.0
2,6.0,7.0,8.0
3,9.0,10.0,11.0


In [26]:
series2 = pd.Series(np.arange(3), index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [27]:
frame

,b,d,e
0,0.0,1.0,2.0
1,3.0,4.0,5.0
2,6.0,7.0,8.0
3,9.0,10.0,11.0


In [28]:
frame + series2

,b,d,e,f
0,0.0,NaN,3.0,NaN
1,3.0,NaN,6.0,NaN
2,6.0,NaN,9.0,NaN
3,9.0,NaN,12.0,NaN


In [29]:
series2

b    0
e    1
f    2
dtype: int64

In [44]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), columns=list("bde"), index=["Utah", "Ohio", "Texas", "Oregon"])
frame

,b,d,e
Utah,0.785150,0.475854,0.036557
Ohio,-0.822238,1.063471,-1.117792
Texas,-0.552987,0.476768,-1.050645
Oregon,-0.491822,-0.971098,0.289286


In [45]:
np.abs(frame)

,b,d,e
Utah,0.785150,0.475854,0.036557
Ohio,0.822238,1.063471,1.117792
Texas,0.552987,0.476768,1.050645
Oregon,0.491822,0.971098,0.289286


In [8]:
def f1(x):
    return x.max() - x.min()


# frame.apply(f1, axis='columns')


# Posso utilizar o apply para aplicar funções python aos DataFrames e Series

In [47]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [48]:
frame.apply(f2)

,b,d,e
min,-0.822238,-0.971098,-1.117792
max,0.785150,1.063471,0.289286


In [35]:
#Função que entrega os valores do DataFrame formatado, ao invés de applymap, posso usar somente map

def my_format(x):
    return f"{x:.1f}"


frame.map(my_format)

,b,d,e
Utah,-0.1,0.4,-0.4
Ohio,0.9,0.1,1.4
Texas,0.8,0.1,-0.6
Oregon,1.1,0.8,1.2


In [36]:
frame['e'].map(my_format)

Utah      -0.4
Ohio       1.4
Texas     -0.6
Oregon     1.2
Name: e, dtype: object

In [9]:
df = pd.DataFrame(np.arange(16).reshape((4, 4)), columns=list('ABCD'), index=['UM', 'DOIS', 'TRÊS', 'QUATRO'])
df

,A,B,C,D
UM,0,1,2,3
DOIS,4,5,6,7
TRÊS,8,9,10,11
QUATRO,12,13,14,15


In [11]:
df.apply(f1, axis='index')

A    12
B    12
C    12
D    12
dtype: int64

In [70]:
s = pd.Series(np.arange(4), index=['4', '3', '1', '2'])
s

4    0
3    1
1    2
2    3
dtype: int64

In [71]:
s.sort_index()

1    2
2    3
3    1
4    0
dtype: int64

In [75]:
f = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list('BCA'), index=['3', '2', '0', '1'])
f


,B,C,A
3,0,1,2
2,3,4,5
0,6,7,8
1,9,10,11


In [ ]:
f.sort_index()

,B,C,A
0,6,7,8
1,9,10,11
2,3,4,5
3,0,1,2


In [87]:
obj = pd.Series(['3', '4', '2', '1'])
obj.sort_index(ascending=False)

3    1
2    2
1    4
0    3
dtype: object

In [88]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

,b,a
0,4,0
1,7,1
2,-3,0
3,2,1


In [91]:
frame.sort_values(["a", "b"])

,b,a
2,-3,0
0,4,0
3,2,1
1,7,1


In [122]:
f = pd.DataFrame(np.arange(12).reshape((4, 3)))
f


,0,1,2
0,0,1,2
1,3,4,5
2,6,7,8
3,9,10,11


In [108]:
f.rank(method='first', axis='index')

,0,1,2
0,1.0,1.0,1.0
1,2.0,2.0,2.0
2,3.0,3.0,3.0
3,4.0,4.0,4.0


C:\Users\FELIPE\AppData\Local\Temp\ipykernel_20380\2782062324.py:1: FutureWarning: RangeIndex.is_numeric is deprecated. Use pandas.api.types.is_any_real_numeric_dtype instead
  f.index.is_numeric()


True

In [125]:
f.cumsum(axis='columns')

,0,1,2
0,0,1,3
1,3,7,12
2,6,13,21
3,9,19,30


In [126]:
f.pct_change()

,0,1,2
0,NaN,NaN,NaN
1,inf,3.000000,1.500
2,1.0,0.750000,0.600
3,0.5,0.428571,0.375
